name: Setup CI

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
