const packageOrder: string[] = [
  "$schema",
  "name",
  "version",
  "private",
  "type",
  "description",
  "keywords",
  "repository",
  "homepage",
  "bugs",
  "license",
  "author",
  "contributors",
  "funding",
  "files",
  "types",
  "typings",
  "main",
  "module",
  "browser",
  "imports",
  "exports",
  "bin",
  "man",
  "directories",
  "scripts",
  "config",
  "dependencies",
  "devDependencies",
  "peerDependencies",
  "peerDependenciesMeta",
  "bundledDependencies",
  "optionalDependencies",
  "overrides",
  "engines",
  "devEngines",
  "os",
  "cpu",
  "packageManager",
  "publishConfig",
  "workspaces",
];

const tsconfigOrder: string[] = [
  "$schema",
  "extends",
  "files",
  "include",
  "exclude",
  "references",
  "compilerOptions",
  "watchOptions",
  "typeAcquisition",
];

export { packageOrder, tsconfigOrder };
